### ISSUE TITLE
Use own/custom Snowplow events along with the GA mirroring

### ISSUE THREAD

**Issue by ohmycto** [snowplow-incubator/snowplow-google-analytics-plugin#10]
Hi there!

First of all, thanks for this really cool thing!

I want to mirror GA events to Snowplow collector, but I also want to have an ability to use custom JavaScript Snowplow events, not only events from GA. How can this be done? `window.snowplow` function is not accessible when using this plugin.

Thanks!

**Comment by BenFradet** [comment]
Hey, 

Could you ask your support questions in [our Discourse](https://discourse.snowplowanalytics.com/) so that everyone can benefit from them.

However, this does not replace the [snowplow-javascript-tracker](https://github.com/snowplow/snowplow-javascript-tracker/), it's just a complement for people using GA.
